### PR TITLE
split KeplerGLBase

### PR DESCRIPTION
**Pull request by hhaensel**
This PR addresses #7 to split off KeplerGLBase.

### CODE REVIEW

**Comment by montyvesselinov** [comment]
I hope this can be merged so we can propose more changes. thank you!

**Comment by montyvesselinov** [comment]
I hope this can be merged so we can propose more changes. thank you!

**Comment by hhaensel** [comment]
It seems that we still need to make a compat entry for KeplerGLBase. Shall I do that here?

**Comment by jmboehm** [comment]
Ah, yes please. I always forget those...

**Comment by hhaensel** [comment]
I still need to fix the location of the test map....

**Comment by hhaensel** [comment]
One question concering tests.
Shall we keep the tests in KeplerGL? Everything has been tested in KeplerGLBase.

We could keep a minimal test, like exporting where Blink is needed. What do you think?

**Comment by hhaensel** [comment]
Hm, probably difficult without a mapbox token...

**Comment by jmboehm** [comment]
Ideally we'd keep stuff that requires the frontend in the tests, such as the png export. I've provided a mapbox token as secret that we can use (as long as it doesn't run too often!). If you add the following line to an "env" in `ci.yml`, I think you should be able to access MAPBOX_KEY as an environment variable. 🤞 

```
MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
```

**Comment by jmboehm** [comment]
Alright, I'm not sure why this doesn't work, but I'll merge this and will try to sort out the mapbox token issue in the next few days. Thanks a lot for the PR.

**Comment by hhaensel** [comment]
Maybe I'm doing something wrong with the MAPBOX_KEY. @jmboehm could you review, please?

**Comment by hhaensel** [comment]
@jmboehm 
Most probably the secret must simply be shifted some lines up ...
EDIT: together with a new `env:` section

**Pull request merged**
