### PR TITLE
Fix tests, docs

### PR DESCRIPTION
**Pull request by jmboehm**

### CODE REVIEW

**Comment by hhaensel** [comment]
You took the same steps as I did, so go ahead. At least your windows cases are passing!

**Comment by hhaensel** [comment]
You made Ubuntu pass, cool!

**Comment by jmboehm** [comment]
The trick was to have `xvfb-run` as a prefix for the julia run. But I can't figure out how to do this on osx, so I've removed those tests for now...

**Comment by hhaensel** [comment]
Fair enough, the package will work anyhow, even if the tests don't pass

**Comment by hhaensel** [comment]
Looking forward to the release ;-)

**Pull request merged**
